example.property= I AM DEV
server.port=8081
spring.datasource.url = jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username =balo
#spring.datasource.password ={cipha}f8848400d62a68d38b0e78f8243a187777425f5051d4fb859bf071503a61cb7f
spring.datasource.password =Lanrebalo@26
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always



management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoints.heath.show-details=always


#Resilience4j properties
resilience4j.circuitbreaker.instances.inventory-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventory-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventory-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventory-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventory-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventory-service.automatic-transition-from-open-to-half-open-enabled=true

