scrape_configs:
  - job_name: 'spring-cloud-services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://eureka-server:8761/eureka'

    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application

      - source_labels: [__meta_eureka_instance_host, __meta_eureka_instance_port]
        separator: ':'
        target_label: instance
